### ISSUE TITLE
Storing large data frames

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#330]
### Issue

From the notebook, suppose that I load a large dataframe of shape (1M, 1k) let's say. I try to store it: it takes a lot of time.

### Expectation

I would like a warning to the user that his file is too big, or maybe just store a subset of the big Dataframe (and warning that the display of the dashboard is truncated). Indeed, no one needs to visualize a dataframe of shape (1M, 1k) in the dashboard.

**Comment by tuscland** [comment]
Discussed with @fcharras that suggested to have a look at DeltaLake, and parquet files.
