### ISSUE TITLE
feat (UI): Export view's items as downloadables

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#339]
From the dashboard, it should be possible to export a graph in high resolution. For example, you send the report to the marketing team, that would like to extract a specific graph for their C-level slides.

**Comment by rouk1** [comment]
I need some clarification. 
Which output format should be proposed to the user ? What is the user journey ?
What kind of plot are exportable and how ?

We support plotly, vega and already rasterized plots, what would be the UI for all those cases ?

**Comment by anasstarfaoui** [comment]
Let me design screens, I'll add them there

**Comment by tuscland** [comment]
@rouk1 we also support primitive objects, numpy arrays, series, dataframes… All can be downloaded or copied in the clipboard (for small items).

**Comment by rouk1** [comment]
> @rouk1 we also support primitive objects, numpy arrays, series, dataframes… All can be downloaded or copied in the clipboard (for small items).

I renamed the issue to reflect that point.

**Comment by tuscland** [comment]
Here is a mapping of types and expected behaviors:

- **primitive types:**
  - copy JSON to clipboard (note: [memory limits can be ignored](https://stackoverflow.com/questions/11137940/maximum-size-of-clipboard-in-current-browsers#:~:text=Most%20data%20is%20copied%20as,on%20browser%20or%20windows%20clipboard.) as long as we are able to provide a reference to the data)
  - download as JSON text
- **numpy array:**
  - copy to clipboard: as a list of numbers, use `numpy.savetxt` default format to format numbers (`%.18e`).
  - download as '.txt': [`numpy.savetxt`](https://numpy.org/doc/2.0/reference/generated/numpy.savetxt.html) with default options (we could add a configurator later)
  - download as '.npy': [`numpy.save`](https://numpy.org/doc/2.0/reference/generated/numpy.save.html) format with option `allow_pickle=False` (platform-independent representation)
  - ⚠️ Do we support numpy v1 and v2? I guess we should.
- **pandas series:**
  - copy to clipboard as string: [`pandas.Series.to_string`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_string.html)
  - download as '.csv': [`pandas.Series.to_csv`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_csv.html)
- **pandas DataFrame:**
  - copy to clipboard as csv: [`pandas.DataFrame.to_clipboard`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_clipboard.html)
  - download as '.csv': [`pandas.DataFrame.to_csv`]
  - download as '.parquet': [`pandas.DataFrame.to_parquet`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_parquet.html)
- **Media Item:**
  - _when media type matches `text/*`:_
    - copy as text
    - download as 'txt' (UTF-8 text)
    - ⚠️ Note: use item's text encoding to decode bytes to UTF-8
    - ⚠️ Note: match [popular media types](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types) with extensions (e.g. md, csv, css, xml, js, txt, etc.)
  - _when media type matches `image/svg+xml`:_
    - copy as text
    - download as 'svg' (UTF-8 text)
  - _when media type matches `image/*`:_
    - copy as image (bytes ?)
    - download as image (bytes ?)
    - ⚠️ Note: match [popular media types](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types) with extensions (e.g. jpg, png, tiff, bmp, webm, etc.)
  - _when media type matches `application/vnd.vega.v5+json`:_
    - copy as image
    - download as 'png'
    - Note: see [vega documentation on image export](https://vega.github.io/vega/docs/api/view/#image-export)
  - _when media type matches `application/vnd.plotly.v1+json`:_
    - copy as image
    - download as 'png'
    - Note: I found a hint on [plotly forums](https://community.plotly.com/t/copy-image-to-clipboard/10355/10), hopefully this is helpful
  - _when media type matches `application/*`:_
    - copy as bytes
    - download as bytes
    - ⚠️ Note: match [popular media types](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types) with extensions (e.g. xls, pdf, zip, etc.)
- **scikit-learn estimator:**
  - download as skops

**Comment by anasstarfaoui** [comment]
Here is a link to the flow, let me know if it's unclear :)
https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Mandr---Workstation---High-fidelity-mock-ups---Q3?node-id=3722-6250&t=OUzJIl8WzxESjBk2-4
![image](https://github.com/user-attachments/assets/e4a0064a-4d9c-4b23-b33a-7db30f5cc1b2)

**Comment by tuscland** [comment]
Wording adjustments:
- "Details" button title: rename to "More"
- "Export graph" menu item label: rename to "Export"
- "Export as a CSV" menu item label: rename to "Export as CSV", repeat for all similar menu items.

**Comment by anasstarfaoui** [comment]
Thank you @tuscland , updated

**Comment by tuscland** [comment]
@rouk1 is it ready for dev, or do you have further questions about this feature?

**Comment by rouk1** [comment]
Sounds ok to me. We need to discuss the implementation and split it in subtasks.

**Comment by thomass-dev** [comment]
I will take a brief look for the backend implementation.

**Comment by sylvaincom** [comment]
List of priorities suggested by @MarieS-WiMLDS and I:

1. media (such as figures)
    1. other images: jpg, png, svg
    1. supported python libraries: matplotlib, plotly, altair
    1. export format: png, pdf, html
1. pandas dataframe
1. scikit-learn estimator
1. pandas series
1. numpy arrays
1. primitive types

**Comment by tuscland** [comment]
Superseded by #487
