### ISSUE TITLE
Dataframe display: displaying the row index

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#376]
When displaying pandas data frames on the dashboard, I would like to have the row index (same as the column index that already appears):
<img width="516" alt="Capture d’écran 2024-09-23 à 15 06 57" src="https://github.com/user-attachments/assets/a0df962e-59fa-41a3-911f-e30604287bd2">

**Comment by augustebaum** [comment]
Yeah, it's a problem indeed. We could at least send the index over as a column when we find it.

**Comment by thomass-dev** [comment]
The index is already sent to the frontend because we use the `tight` [orientation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html) during serialization: 

```python
>>> df.to_dict('tight')
{'index': ['row1', 'row2'], 'columns': ['col1', 'col2'],
 'data': [[1, 0.5], [2, 0.75]], 'index_names': [None], 'column_names': [None]}
 ```
