### ISSUE TITLE
Display bug: the up and down arrows for cells do not appear

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#377]
When on the dashboard, the up and down arrows to move cells do not appear (but are still clickable and work fine):
<img width="313" alt="Capture d’écran 2024-09-23 à 15 18 49" src="https://github.com/user-attachments/assets/7d7e8954-1cc5-49a8-a24f-9a947d478355">

**Comment by rouk1** [comment]
Those arrows will disappear in #336. 
Then some real drag'n'drop UX may arrive #408.

So I close this one.
