### ISSUE TITLE
Add capabilities to drag'n'drop card in the layout

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#408]
# Feature Request

_User cant reorganize easily there cards in the view builder._

One solution is to add a handle to each cards and implement a drag'n'drop system to reorder cards.
One alternative coudl be to use a dedicated grid layout library like [grid layout plus](https://grid-layout-plus.netlify.app/)

> Here is a link to the drag&drop flow @rouk1  : https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Mandr---Workstation---High-fidelity-mock-ups---Q3?node-id=3632-3791&t=r3d92IJPyjWvDeVI-4 

 _Originally posted by @anasstarfaoui in [#326](https://github.com/probabl-ai/skore/issues/326#issuecomment-2382379271)_

**Comment by rouk1** [comment]
This will be fixed (hopefuly 😞 ) by #489

**Comment by augustebaum** [comment]
Is this solved?

**Comment by thomass-dev** [comment]
Solved by #489
