### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#411]
Here are a few things we would like to improve in the README:
- [x] The badge at the top results in a broken image
- An introductive section is missing:
  - [x] it should first describe what skore is about: an all-inclusive library for data scientists, with a current focus on offering easy results tracking. (suggestion to improve)
  - [x] it should specify with humility that this is a work in progress, that we benefit from user's feedback, and why not giving us a star.
  - [x] Add link to Discord server
  - [x] A screenshot or two, or even better, an animated gif.
- I would love to see a "Use cases" section where we describe a few ways of using skore.
- [x] The "Quick start" section is overwhelming. I prefer a large chunk of code instead of individually (copy-able) bits. A link to the examples folder can be added.
- [x] Finally, the "Roadmap" section is not a roadmap at all and is too vague. Let's remove it for now.

**Comment by sylvaincom** [comment]
WIP at https://github.com/probabl-ai/skore/pull/413
