### ISSUE TITLE
User Guide and API documentation

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#412]
The README will shortly show its limits, so we want to develop a proper documentation.

From a bird's eye view, we need:

- Content: at minimal, an expanded version of the README, and the API reference.
- Hosting: a place to host the documentation, GH pages?
- Version control: make it so future documentation is available as pre-release, and also host older versions (just like scikit-learn docs).

**Comment by augustebaum** [comment]
I think [Material for MkDocs](https://squidfunk.github.io/mkdocs-material) is a good starting point (used by FastAPI)

**Comment by tuscland** [comment]
This is a good suggestion.

Just note that we should do a quick due diligence and compare it to sphinx (actually, the theme used by scikit-learn), and collect pros and cons. I know some people in the team would like us to follow unified conventions, but we can break them if we know there are a good reasons.

**Comment by tuscland** [comment]
We should use the same theme and system as scikit-learn (PyData theme for sphinx).

**Comment by thomass-dev** [comment]
Closed by #553 #582 #584.
