### ISSUE TITLE
Adjust primary programming language skore repo

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#415]
We would like to show users that skore is primarily a Python project (because this is what they might use as their working language).

As per [linguist](https://github.com/github-linguist/linguist/blob/main/docs/overrides.md), here's a suggested configuration:
- Create a `.gitattributes` file
- Add this statement: `*.vue linguist-detectable=false`

This should help bring Python as the main language.
Note, I have not been able to test it because I have not been able to install github-linguist.

**Comment by augustebaum** [comment]
For the record, acting as though we have no Vue code in our codebase is a strange way to say that skore is primarily a Python project. I think this problem could be equally solved by being explicit in our README, e.g. having somewhere in the first few lines: "skore is a data science library for the Python ecosystem which includes a Python library and a Vue frontend application."

**Comment by tuscland** [comment]
<img width="774" alt="image" src="https://github.com/user-attachments/assets/ab6df19b-32cf-44de-97ed-54f821d998d3">

<img width="337" alt="image" src="https://github.com/user-attachments/assets/0ac6adbe-454f-445c-8f7b-97cb1f5b4c47">
