### ISSUE TITLE
chore: Readme file uses assets that are outside of the repo

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#468]
### Which part of the documentation needs improvement?

README.md

### Describe the problem found in the documentation

The README uses a static html asset and a gif. 

### Suggested improvement

Those assets should be hosted within the repo.

**Comment by sylvaincom** [comment]
[WIP] I will create the documentation page of the skore repo (see https://github.com/probabl-ai/skore/issues/412) in a `doc` folder using the [PyData Sphinx 2024](https://github.com/pydata/pydata-sphinx-theme) theme, and will put the files for the README in that `doc` folder

**Comment by sylvaincom** [comment]
@tuscland also suggests storing as a git-LFS (https://github.com/probabl-ai/skore/pull/472#discussion_r1804401741)

**Comment by sylvaincom** [comment]
@thomass-dev could you link the according PR and close this issue now that you set up GIT LFS? 🙏
