### ISSUE TITLE
Improve README - V2

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#469]
### Which part of the documentation needs improvement?

README.md

### Describe the problem found in the documentation

- [x] The intro text is wayyyy too long. Nobody will read it ;)
- [x] The `basic_usage.ipynb` is not basic enough, and this makes the presentation gif too long, and too exhaustive. I suggest we split the `basic_usage.ipynb` in two:
  - basic_usage: demonstrates only putting a dict with two values, and a plot.
  - demo: exhaustively demonstrates all features and item types.
  - This would allow for a shorter intro video.
- [x] We should use the light theme for all screenshots and videos.
- [x] The video was too fast, it should be shorter, but also slower.
- [x] The narrative of the video should set-up the initial context more clearly.
- [x] The GIF should be under 10 MB.
- [x] The quickstart section is too long. Only replicate what is in the new basic_usage.
- [x] There is a === in the readme
   <img width="197" alt="Screenshot 2024-10-10 at 10 20 52" src="https://github.com/user-attachments/assets/12d95ff3-71aa-46fa-af88-6edf84c76026">
- [x] Invert "create a new view" before you can visualize it.
- [x] Once @thomass-dev has adaptedn the code to be compliant on `python>=3.9`, specify it in the installation part

**Comment by tuscland** [comment]
There is a PR ongoing to improve the README, please add a comment instead.

**Comment by tuscland** [comment]
@sylvaincom note that #483 might be included here as well.

**Comment by augustebaum** [comment]
Additional thing to do: the probabl logo at the bottom is hard to read when github is in dark mode; can we add a light background to the image?

**Comment by tuscland** [comment]
> I just noticed something else: the probabl logo at the bottom is hard to read when github is in dark mode; can we add a light background to the image?

Good catch!
Maybe we can [go fancy](https://stackoverflow.com/questions/65413712/changing-readme-md-image-display-conditional-to-github-light-mode-dark-mode) ;)

**Comment by augustebaum** [comment]
Dark mode is too experimental for this to work reliably I think

**Comment by sylvaincom** [comment]
replaced by the orange logo so looks good on both light and dark themes
