### ISSUE TITLE
Rethink Views System

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#476]
**Description:**
Users are confused by the distinction between views and elements. They struggle to understand the hierarchical relationship, making navigation and interaction difficult.

**User Story:**
As a user, I want a clearer and more intuitive views system, so that I can easily navigate between views and elements without confusion.

**Acceptance Criteria:**

- A clear definition and explanation of views vs. elements is presented in the UI.
- The interface visually differentiates views from elements in a meaningful way.
- Navigation between views and elements is simplified.

**Comment by anasstarfaoui** [comment]
Hey, based on thursday user testing, we saw that we might have some issues on "views" understanding
So I worked on several approach on how we could it improve it. I wanted to have a support to start conversation.
You can find the designs propositions here :  https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Mandr---Workstation---High-fidelity-mock-ups---Q3?node-id=3910-4411&t=UsL81RJwSPGNwSFQ-4

**Comment by anasstarfaoui** [comment]
cc @rouk1

**Comment by rouk1** [comment]
So... shall we decide something here ?
As a quick workaround I propose to add a default view that is selected by default.

**Comment by anasstarfaoui** [comment]
I think we can state that we choose this direction, move the views panel and a default view that we cannot delete. Thoughts ?
![image](https://github.com/user-attachments/assets/09465f93-38ac-48b8-bf77-1347f3173d48)

**Comment by tuscland** [comment]
Yes, go for it.

**Comment by rouk1** [comment]
Could we use a modal for renaming views ? 
I we want to move fast this is easier as it forces the user to finish it's renaming action, hence getting rid of corner cases around pending name views.

**Comment by anasstarfaoui** [comment]
I think we really should use modal in last case, it's the most interrupting pattern from a UX perspective, so I would avocate to find another way to do it if it's possible

**Comment by MarieS-WiMLDS** [comment]
I feel more comfortable with the first option. It makes a clear difference between views & items. I understand clearly where I am and how can I change.  
My only question is how do we manage views in this system? for instance if I want to change the name of a view, or delete it?

**Comment by anasstarfaoui** [comment]
![image](https://github.com/user-attachments/assets/23d82376-6ff7-4dab-9c7f-fdb82b1c951f)
For now, something who could be like this

**Comment by MarieS-WiMLDS** [comment]
ok, thanks for the precision!

**Comment by sylvaincom** [comment]
Same as @MarieS-WiMLDS, I prefer option 1

**Comment by anasstarfaoui** [comment]
Okay then the screen are already ready in the V.4 part of figma, link here:
![image](https://github.com/user-attachments/assets/528a26e5-e3e1-4761-bc16-bbab8d6eb626)


No one see an objection on passing this ticket to ready to dev ?

**Comment by MarieS-WiMLDS** [comment]
all good for me!
