### ISSUE TITLE
Stop `nbstripout` from re-assigning cell IDs

### ISSUE THREAD

**Issue by augustebaum** [probabl-ai/skore#482]
By default nbstripout makes cells IDs sequential (first cell has ID "1", etc.), which leads to huge diffs in small PRs (e.g. if you add a cell at the start of the notebook, all the cell IDs will be changed). This in turn generates a lot of merge conflicts.

We should use nbstripout's [`--keep-id` flag](https://github.com/kynan/nbstripout?tab=readme-ov-file#keeping-some-output).

**Comment by thomass-dev** [comment]
Its a bit weird to have non sequential cell ids. I'd prefer to keep this cleaning in state.

**Comment by augustebaum** [comment]
I'd argue the opposite; it's weird to change IDs when the content hasn't changed. For example, see [this diff](https://github.com/probabl-ai/skore/pull/443/files#diff-e257c5f78b0858ed310932e5c35c0471da720731d211b324be222b0d9de9fbff): all I did was add one cell in the middle of the notebook, but `nbstripout` changed all the IDs of the cells after it.

**Comment by tuscland** [comment]
If the ids are used as implementation details, there's no reason to keep them incremental.

**Comment by thomass-dev** [comment]
The ids appear in the notebook, in the left-hand sidebar, don't they?

**Comment by thomass-dev** [comment]
Seen together, this ID is not shown.
