### ISSUE TITLE
Ability to see results as they are added to a project

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#485]
### Is your feature request related to a problem? Please describe.

Some users find it cumbersome to be forced to add an item to a view before being able to see it. One might want to see the stream of items as they are created.

### Describe the solution you'd like

A read-only view that infinitely scrolls and display the list of the recently created items by descending order.

### Additional context

Related to #370 and #476

**Comment by augustebaum** [comment]
Relatedly, it's a bit strange that when you first start working on a project, no view exists, so you can't add an element to the canvas on the right. Having this stream view as default might make sense.

**Comment by tuscland** [comment]
cc @anasstarfaoui

**Comment by anasstarfaoui** [comment]
I'm sorry, I don't understand really well this ticket ?

**Comment by anasstarfaoui** [comment]
![image](https://github.com/user-attachments/assets/e445e485-ae7d-4f36-b443-15c3d07df7fc)
Proposition

**Comment by anasstarfaoui** [comment]
![image](https://github.com/user-attachments/assets/251d4d8a-e0cc-4d4c-970d-a6ea457df0d9)
Proposition, waiting for you thoughts on how clear it looks

**Comment by augustebaum** [comment]
> Proposition, waiting for you thoughts on how clear it looks

I think I would expect to see the item contents in this special view, not just that it was created

---

Maybe it could be a toggle on a View ("auto-add"?) that, if turned on, makes it so whenever an item is `put`, it is automatically appended to that view.

Currently when we create a Project we immediately create a View called "default", so we could give that toggle to that View.

**Comment by tuscland** [comment]
Superseded by #767
