### ISSUE TITLE
feat(UI): Show the name of the indexes in dataframe widget

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#495]
In a next iteration, i propose to nicely show the name of the indexes. For instance, 

![image](https://github.com/user-attachments/assets/18aa814c-d1ee-4e5b-b021-4e54cec3d170)

_Originally posted by @thomass-dev in https://github.com/probabl-ai/skore/issues/493#issuecomment-2413829457_
            
---

It should be pertinent on a dataframe with multi-indexes.            

```python
In [6]: import pandas as pd
   ...: 
   ...: df = pd.DataFrame([{"age": ">70", "number": "1M", "gender": "M"}])
   ...: df.index = pd.MultiIndex.from_arrays([["france"], ["paris"], ["1"]], names=('country', 'city', 'district'))

In [7]: df
Out[7]: 
                        age number gender
country city  district                   
france  paris 1         >70     1M      M
```

**Comment by thomass-dev** [comment]
@anasstarfaoui what do you think? Multi-index means that a row can have a composed identifier.

**Comment by thomass-dev** [comment]
@sylvaincom @MarieS-WiMLDS is it relevant for a DS to have details over multi-index? Actually, its 
 
 https://github.com/probabl-ai/skore/pull/493#issue-2588285175

**Comment by MarieS-WiMLDS** [comment]
yes, it can happen sometimes to use dataframes with multi-indexes due to group_by!
