### ISSUE TITLE
feat(UI): Nicely show the name of the indexes

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#496]
In a next iteration, i propose to nicely show the name of the indexes. For instance, 

![image](https://github.com/user-attachments/assets/18aa814c-d1ee-4e5b-b021-4e54cec3d170)

_Originally posted by @thomass-dev in https://github.com/probabl-ai/skore/issues/493#issuecomment-2413829457_

**Comment by rouk1** [comment]
@thomass-dev could you elaborate and give an example datatable json or code ?

**Comment by thomass-dev** [comment]
Closed in favor of https://github.com/probabl-ai/skore/issues/496
