### ISSUE TITLE
Train_test_split assist  - improvement A - silence warnings with explanations

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#497]
### Is your feature request related to a problem? Please describe.

As a data scientist, I want to be guided in the choice of the arguments in the scikit-learn train_test_split function, without having too many warnings to avoid being over my cognitive budget charge (let's say: 2 warnings max).  
It's a follow-up of issue https://github.com/probabl-ai/skore/issues/492.  
As a data-scientist, I want to be helped about how I can silence warnings.  

### Part 1 - explain that warnings can be silenced.

Before all the warnings, link to doc on how they can be silenced. 

### Part 2 - docs & "language structure"

Decide a structure to indicate how to silence a warning. Suggestion from Olivier: get inspiration from linting ignore.  
"To silence a warning, explain why for your fellow data scientists (include your future you)."

### Part 3 - create a button next to warnings

 Next to warning, create a button to automatically update the code to silence warning + start a comment, something like "explain why you can silence this warning here" (feasibility to be checked).

**Comment by sylvaincom** [comment]
*How can the user set the amount of warnings he wants to receive / silence?*

This reminds me of the `verbose` parameter.
*Example*: [`GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)

This `verbose` parameter could be set globally as a configuration parameter.
*Example*: https://seaborn.pydata.org/generated/seaborn.set_theme.html

**Comment by MarieS-WiMLDS** [comment]
Closing this epic as it's most likely going to be rewritten completely when we rewrite warnings UX.
