### ISSUE TITLE
Toasts must be dismissed manually

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#499]
### Is your feature request related to a problem? Please describe.

When a warning or an error is generated in skore-ui, a toast appears. The toast remains displayed until I manually click "dismiss".

### Describe the solution you'd like

- I want to automatically dismiss toasts after some time (20 seconds).

### Additional context

Possible enhancements:
- I would like to see that toasts will be dismissed, so that I have no cognitive load when a toast appears.
- I want to cancel the timeout so that I can keep on reading the toast.
- Finally, when a toast is automatically dismissed, I want to find it back in a notification center as an unread notification.

**Comment by augustebaum** [comment]
We can start by implementing auto-dismissal after a timeout. If so, this is ready for dev.

**Comment by rouk1** [comment]
As discusses with @anasstarfaoui we will go for something a little bit more fancy.

![Image](https://github.com/user-attachments/assets/174b8c70-dfa5-4a20-953c-6337ac59fbcd)

**Comment by anasstarfaoui** [comment]
https://www.figma.com/design/MRo6JXvZX49ODk1KKzDVJl/Design-system?node-id=151-42&t=cCni6nVa7EjKOAq6-4

-> link to design system toast page
