### ISSUE TITLE
chore: Ensure CLI is covered by test at 100%

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#508]
Part of #475 , next step after https://github.com/probabl-ai/skore/pull/479 .

---

To be Windows-compliant, we need to ensure that all CLIs are executable.

**Comment by thomass-dev** [comment]
I've just create a branch to referenced in #475 .

**Comment by sylvaincom** [comment]
Thanks, let me know when I have to make changes to the README like adding instructions or adding a badge

**Comment by augustebaum** [comment]
This issue isn't very actionable. Maybe we could add a workflow that fails if coverage is not 100%?
