### ISSUE TITLE
Add view button is too small

### ISSUE THREAD

**Issue by koaning** [probabl-ai/skore#509]
### Is your feature request related to a problem? Please describe.

When you just start using the app you need to make a view first before the cliking and dragging can commence. It felt like the app was broken until I learned that there is a button to press. 

However, it took a while for me to find said button. 

![image](https://github.com/user-attachments/assets/5580c6c0-1a3f-4019-94d9-c223fa727902)

Could the button be made bigger? Maybe also with a hint if there is no view that it is the button to press?

### Describe the solution you'd like

See above. 

### Describe alternatives you've considered, if relevant

- [ ]

**Comment by tuscland** [comment]
The view button should be a clear + sign inside the button's frame.

Related to #532
