### ISSUE TITLE
On hover interaction suggests click, no hover

### ISSUE THREAD

**Issue by koaning** [probabl-ai/skore#510]
### Is your feature request related to a problem? Please describe.

When I hover over a draggable element it looks as if it is meant to click. 

![CleanShot 2024-10-16 at 16 25 07](https://github.com/user-attachments/assets/aaea6dbe-e35a-41cb-abc2-0920054d2932)

### Describe the solution you'd like

Maybe the drag icon should appear on hover to make the intent of the interaction clear?

**Comment by rouk1** [comment]
It's a fair point. But... we add some feedbacks that drag'n'drop is not that easy for some. Hence double click as been introduced. There is a tradeoff...

@anasstarfaoui what do you think ?

**Comment by anasstarfaoui** [comment]
Let's enable both. I'm working on a way to drag&drop and to add with a double click I will add the screen there.

**Comment by tuscland** [comment]
This should be solved by #533
