### ISSUE TITLE
Could we hide the variable name/created/updated date?

### ISSUE THREAD

**Issue by koaning** [probabl-ai/skore#511]
### Is your feature request related to a problem? Please describe.

I cannot help but notice that each element that we put in the view comes with an extra bit of screen real-estate being taken by the create/updated datetimes as well as the name of the item. 

![image](https://github.com/user-attachments/assets/c3bfd513-d833-4da9-be5d-acb0f1a9cc4c)

### Describe the solution you'd like

Do we really need that? To me it feels like no stakeholder would be interested in the name of the variable. Maybe we can hide this metadata in a way that is retreivable but not in your face initially?

**Comment by tuscland** [comment]
The name of the variable is an important information, so it needs to be there.
However, we hear that the real-estate could be improved.
