### ISSUE TITLE
Some methods have a weird signature

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#512]
### Is your feature request related to a problem? Please describe.

```python
from skore import load
project = load("project.skore")
project.put("my_int", 3)
print([method for method in dir(project) if callable(getattr(project, method)) and not method.startswith("__")])
project.put_item?
```
returns
```
Signature: project.put_item(key: str, item: skore.item.item.Item)
```
The `skore.item.item.Item` is quite weird.

### Describe the solution you'd like

I would like something more concise?

**Comment by tuscland** [comment]
It would be nice to make the packages more elegant. It surely looks weird to repeat `item` twice.

**Comment by rouk1** [comment]
Note that Item is aliased in its package [`__init__.py`](https://github.com/probabl-ai/skore/blob/main/skore/src/skore/item/__init__.py).

Hence you can use  

```python
from skore.item import Item
```

**Comment by augustebaum** [comment]
Yep, not sure this is really a problem to be solved. Since we're already exposing `Item` through `skore.item`, I'll go ahead and close this.

By the way, "signature" refers to a function's input and outputs types; what you mean is something like "import path" I guess.
