### ISSUE TITLE
doc: Improve the docstring from the code source so that the documentation API will be clear

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#514]
### Which part of the documentation needs improvement?

_Which part of the documentation needs improvement?_ Documentation API (so enhance the code source docstring). Indeed:

The `skore` documentation will soon be launched (https://github.com/probabl-ai/skore/issues/412). Same as in scikit-learn, there will be an API tab. Actually, what is done in Sphinx documentation is that all the content of the documentation on our classes is automatically built from the docstring of the code source.

### Example with [scikit-learn's logistic regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

The documentation API looks like this:
<img width="500" alt="Capture d’écran 2024-10-17 à 08 57 32" src="https://github.com/user-attachments/assets/7956acf2-c3c6-42fb-9045-af637202c9e5">
...
<img width="500" alt="Capture d’écran 2024-10-17 à 08 56 21" src="https://github.com/user-attachments/assets/7b2ba52f-e274-443d-b362-1d473131f347">

while the corresponding docstring in the code base looks like this:
```python
class LogisticRegression(LinearClassifierMixin, SparseCoefMixin, BaseEstimator):
    """
    Logistic Regression (aka logit, MaxEnt) classifier.
    
    In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
    scheme if the 'multi_class' option is set to 'ovr', and uses the
    cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
    (Currently the 'multinomial' option is supported only by the 'lbfgs',
    'sag', 'saga' and 'newton-cg' solvers.)
```
 ...
 ```python
    Read more in the :ref:`User Guide <logistic_regression>`.

    Parameters
    ----------
    penalty : {'l1', 'l2', 'elasticnet', None}, default='l2'
        Specify the norm of the penalty:

        - `None`: no penalty is added;
        - `'l2'`: add a L2 penalty term and it is the default choice;
        - `'l1'`: add a L1 penalty term;
        - `'elasticnet'`: both L1 and L2 penalty terms are added.
 ```

### Describe the problem found in the documentation

Currently, our docstring is quite poor:
<img width="500" alt="Capture d’écran 2024-10-17 à 09 03 12" src="https://github.com/user-attachments/assets/9bf0255d-47fe-4e2a-8b1d-7910678f8858">

Especially, for machine learning stuff such as `skore.cross_validate`, it will have to be properly documented cc @augustebaum, @MarieS-WiMLDS.

### Suggested improvement

Please write docstring everywhere! For each class, describe its attributes, etc. For each method of each class, document it.

**Comment by sylvaincom** [comment]
Hmm I think we're aiming at DS users that will probably ignore the front end and back end API to focus on ML API such as cross validation and train test splits

But having a minimal clean docstring everywhere is nice to have I think

And very thorough docstring for pure ML stuff

**Comment by MarieS-WiMLDS** [comment]
Should we close this issue now that the documentation has been improved by a lot + there are epics more precise to keep improving?

**Comment by sylvaincom** [comment]
Yes!

**Comment by sylvaincom** [comment]
Yes!
