### ISSUE TITLE
fix(docs): Improve the documentation by adding some example use cases where skore adds value

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#515]
### Which part of the documentation needs improvement?

Examples

### Describe the problem found in the documentation

Currently, in the documentation, the examples only show basic usage of `skore` (how to load, how to put an item, etc).

### Suggested improvement

It would be great to add concrete examples around business cases to showcase the added value of `skore`, how it actually helps a data scientist. Notebooks such as the binary classification from @MarieS-WiMLDS that uses cross validation, or the EDA notebook from @sylvaincom could be adapted to this purpose.

In any case, put more tasks in the cross validation example

**Comment by sylvaincom** [comment]
Related to https://github.com/probabl-ai/skore/issues/592

**Comment by MarieS-WiMLDS** [comment]
indeed, it's even a duplicate. I'm closing the newest issue.

**Comment by sylvaincom** [comment]
Closed by PR https://github.com/probabl-ai/skore/pull/636
