### ISSUE TITLE
UI: Increase overall typography size and button dimensions

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#518]
**Summary**
The current typography size is too small at 12px, making it harder to read. We will increase it to 14px, and also enlarge buttons to improve usability.

**Expected Outcome**
Typography across the app should be updated from 12px to 14px for better readability.
Buttons should be resized to provide a larger click/tap area.

**Acceptance Criteria**

- All text elements (headings, paragraphs, labels, etc.) should use 14px as the minimum size, it will be all some rare items who will be 12px.

- Button size should increase proportionally to maintain padding and spacing.

- Ensure the layout adapts well to the new text and button sizes without breaking.

**Attachments**
I reworked the dark theme with the new font size, I will do it today for white also

Here is the link : https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=3871-9738&t=0kg64QBSvZDbnKy7-4

**Comment by tuscland** [comment]
Please notify here when light theme is ready.
