### ISSUE TITLE
UI: Update icon colors in dark mode from orange to blue

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#519]
Summary
To improve consistency between dark mode and light mode, the icon colors in dark mode will be changed from orange to blue. This will create better harmony across both themes. The new blue color has been added to the color system.

Expected Outcome
Typography across the app should be updated from 12px to 14px for better readability.
Buttons should be resized to provide a larger click/tap area.

Acceptance Criteria
All elements icons in dark mode should change from orange to blue to align with the light mode palette and improve visual harmony.

Attachments
I reworked the dark theme with the new colors, you can find here, also its added inside color system

Here is the link : https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=3871-9738&t=0kg64QBSvZDbnKy7-4

**Comment by tuscland** [comment]
The expected outcome seems to have been copied from #518
