### ISSUE TITLE
UI: Remove the right stroke between topbar elements to avoid a 2px stroke

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#521]
**Summary**
The current shadows in dark mode are too prominent and need to be softened for better visual balance. The goal is to create more subtle, refined shadows to improve the overall aesthetics.

**Expected Outcome**
The right stroke between the topbar elements should be removed to avoid having a 2px stroke. This will result in a more cohesive and visually balanced design.

**Acceptance Criteria**

- Remove the 2px stroke on the right side of the topbar elements.
- Ensure that the layout remains consistent and visually balanced after removing the stroke.

**Attachments**
Here is the actual element to change : 

![Image](https://github.com/user-attachments/assets/2d2c3a77-4ff0-42ba-bbe5-367fb516d745)

**Comment by tuscland** [comment]
It seems an attachment is missing.

**Comment by anasstarfaoui** [comment]
The attachement is the image, but I dont know why it appears on top lol
