### ISSUE TITLE
UI: Allow users to delete a new view before naming it and auto-apply the name when leaving

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#522]
**Summary**
Currently, users cannot delete a new view if they haven't named it yet. We need to allow them to delete the view even before naming. Additionally, when a user leaves the newly created view, the system should automatically apply the default name and remove the orange selection state.

**NOTE : This not true for the default view, who cannot be deleted.**

**Expected Outcome**

- Users should be able to delete a new view even if they haven’t named it yet.
- When a user leaves the newly created view, the system should automatically apply the given name and remove the orange selection.

**Acceptance Criteria**

- Users can delete new views, even when they haven't named the view yet.
- When leaving the newly created view, the default name (e.g., “New view”) is applied.
- The orange selection highlight is removed when the view is no longer active or selected.

**Attachments**
Will add the link shortly with ticket about new views system

**Comment by rouk1** [comment]
Now that views suggested name is automatically incremented, I'll save the view name when closing the dropdown.
