### ISSUE TITLE
UI: Display newly added items at the top of the canvas instead of the bottom

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#523]
**Summary**
When adding new elements to the canvas, the items are currently displayed at the bottom. To improve user experience and provide immediate visual confirmation of the action, new items should be added to the top of the canvas.

**Expected Outcome**
Newly added items should appear at the top of the canvas, giving users instant feedback that the action has been completed successfully.

**Acceptance Criteria**

- When a new item is added to the canvas, it should be positioned at the top rather than the bottom.
- Ensure the display update happens in real-time without affecting the current view or layout.
- Test to confirm that the behavior applies to all types of elements that can be added to the canvas.

**Comment by tuscland** [comment]
I like this, as a quick win.

@MarieS-WiMLDS @rouk1 WDYT?

**Comment by MarieS-WiMLDS** [comment]
When you say top of the canvas, to be sure we talk about the same place, it means the menu on the left?  
![Capture d’écran du 2024-10-18 16-31-22](https://github.com/user-attachments/assets/efa47ea4-16aa-49bb-8e7e-0b79f4767709)  
With this new rule, I would have item2 above item?  

If it's the case, I don't think it's the most important thing we have in our backlog. It's only useful when many items are created.

**Comment by rouk1** [comment]
Are we on the same page ?
I read this as: when you add an item to the view by clicking it (former double click) it appears at the top of the view.
I do not read this as : "We have a live view that display all items."

Anyhow: should we trigger a scroll to the top of the page when an item is added ?

**Comment by anasstarfaoui** [comment]
I mean when we add an item inside a view

**Comment by anasstarfaoui** [comment]
I think it's not a really good idea to be honest... anyway let's test and see
