### ISSUE TITLE
UI: Let’s change the items name to white

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#524]
Summary
The current element names in the sidebar are not easily visible. To improve readability, the element names will be changed to white for better contrast against the dark background.

Expected Outcome
All element names in the sidebar should appear in white, making them clearer and more readable in dark mode.

Acceptance Criteria

- Update all element names in the sidebar to use white text.
- Ensure the text remains legible and does not clash with other elements in dark mode.
- Verify that the color change applies to all states (default, hover, active).

**Attachments**
Here an example : https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=3875-11221&t=0kg64QBSvZDbnKy7-4

**Comment by tuscland** [comment]
Renamed "element" to "item" as per #534
