### ISSUE TITLE
UI: Transition toast messages from white to black and reposition to top-middle

### ISSUE THREAD

**Issue by anasstarfaoui** [probabl-ai/skore#525]
**Summary**
Currently, the toast messages are displayed in white, but I think we can keep the same color for dark and white theme, which is black toasts Additionally, the toast notifications will be repositioned to the top-middle of the screen for better visibility and consistency.

**Expected Outcome**

- Toast messages should appear with a black background in dark mode, matching the current dark theme.
- Toast messages should be repositioned to the top-middle of the screen to provide immediate feedback in a more central location.

**Acceptance Criteria**

- Update the background color of toast messages to black when in dark mode.
- Reposition toast notifications to the top-middle of the screen.
- Ensure that toast notifications are still easily readable and accessible in both dark and light modes.
- Verify that all types of toast messages (e.g., success, error) maintain clear contrast with the new background color.

**Attached**
Here is a link with an example of everything we just said : https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=3875-13277&t=0kg64QBSvZDbnKy7-4

**Comment by tuscland** [comment]
I like this, as a quick win.

@MarieS-WiMLDS @rouk1  WDYT?

**Comment by MarieS-WiMLDS** [comment]
Let's go!

**Comment by rouk1** [comment]
roger that

**Comment by tuscland** [comment]
Sorry folks, I meant to put this comment in #523…
