### ISSUE TITLE
UI: Rename "Elements" to "Items"

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#534]
In order to avoid confusion between the API and the UI, "Elements" should be renamed to "Items".

cc @anasstarfaoui

**Comment by anasstarfaoui** [comment]
Done on the v4 https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4045-9733&t=Q0BUTUQUzs5xvg95-4
