### ISSUE TITLE
`Project.put` `on_error="warn"` by default which is astonishing

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#540]
I see that [`Project.put`](https://github.com/probabl-ai/skore/blob/11aecbac0ea910944d38da2081a7df74f200c882/skore/src/skore/project.py#L42) has an argument `on_error`, this is so when "putting" several items at once (from a dictionary), we want to have the option to log a warning, or raise an error.

 `on_error="warn"` for single value `put`.

This is both surprising and not uniform with other Project APIs (e.g. `get` does not allow to control `on_error`).

We can make it a bit simpler, and remove the `on_error` argument. We would choose a unique behavior for both variants of the function:
- single value `put`: raise immediately.
- multiple value `put`: delay error raise to the end, collecting errors raised during individual `put`.

**Comment by augustebaum** [comment]
The point of `on_error="warn"` is to abide by our golden rule, which is to avoid breaking user's workflows (e.g. stopping a cell in which a long training session took place). I'm happy to remove this if we think this is not a valid concern anymore.

**Comment by tuscland** [comment]
Actually, we never really decided nor committed to that golden rule because it was under discussion [in this issue](https://github.com/probabl-ai/skore/issues/389). When we talked about it, you pointed out very valid issues with adopting this behavior.
My conclusion is:
- we need more user feedback.
- the library should behave as a normal Python library: user errors raise an exception, warning are issued for non-critical errors, and the internals must be robust (i.e. not throw exceptions in edge cases where it could have been avoided).

**Comment by thomass-dev** [comment]
If we would `put_several` to be identical to several `put`, we shoud do 1.
