### ISSUE TITLE
RecursiveDriftAnalysis - follow up of train_test_split: help to detect the drift on a dataset

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#550]
### Is your feature request related to a problem? Please describe.

As a Data Scientist, I want to know if there is drift in my dataset, and on which columns.  
I want to be able to precise on which column the dataset should be read (index? one column in particular?). 

### Describe the solution you'd like

We could use the solution described in https://github.com/probabl-ai/skore/issues/498, but I think it actually requires more user & market research before that.

**Comment by tuscland** [comment]
@Vincent-Maladiere convinced us that this is too advanced for now.
