### ISSUE TITLE
Cross_validate - improvement B.1 - Compare several cross_validate

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#557]
### Is your feature request related to a problem? Please describe.

As a DataScientist, I want to be able to compare the several cross_validation I did.  

### Describe the solution you'd like

![371590757-d7d2ff40-f163-46cf-a002-89dbf06661a3](https://github.com/user-attachments/assets/ef55b47d-49d1-4e8d-b505-51c1a7d86d4c)  
In a first iteration, to simplify things, the user will have to say when it's comparable. By default, everything lands in the same plot. As a user, I must be able to delete some runs (in case I ran too many of them).  
The "information" panel must display:  
- the training dataframe name + its uuid
- when relevant, the target name and its uuid
- the estimator name & parameters

The dataframe & the target are not saved because it would be too heavy. However, to recognize them, we can save: 
- their hash
- the following set {nb_col, nb_rows}. This is suboptimal, but good for an MVP. In an iteration, we can think about storing a skrub table report.

**Comment by tuscland** [comment]
Superseded by #803
