### ISSUE TITLE
Inconsistent licenses in Readme, Pypi and github "about" section

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#559]
### Describe the bug

![2024-10-21_16-52](https://github.com/user-attachments/assets/a487f3f9-d155-4415-acc5-4cb110a579c9)

### Steps/Code to Reproduce

open https://github.com/probabl-ai/skore :) 

### Expected Behavior

Consistant licences are displayed

### Actual Behavior

Different licenses are displayed

### Environment

```shell
N/A
```

**Comment by augustebaum** [comment]
Two things to deal with:
- [ ] license is shown as dynamic in pyproject.toml, and
- [ ] pyproject.toml has the tag "License :: OSI Approved :: BSD License" .

**Comment by thomass-dev** [comment]
I think the problem came from the tag `License :: OSI Approved :: BSD License`.
