### ISSUE TITLE
feat: Enhance skore.cross_validate with average and standard deviation

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#562]
### Is your feature request related to a problem? Please describe.

As a data scientist, I want to see the average of barplots displayed, and +/- standard-deviation. 

Sub issue of https://github.com/probabl-ai/skore/issues/544 

### Describe the solution you'd like

- [ ] Add the average and std on the plots, as done in the [scikit-learn MOOC](https://inria.github.io/scikit-learn-mooc/predictive_modeling_pipeline/02_numerical_pipeline_video_cross_validation.html):
<img width="550" alt="Capture d’écran 2024-10-21 à 11 06 05" src="https://github.com/user-attachments/assets/5f42c1ca-3aad-4ca0-b382-57d328f7a3c4">

**Comment by augustebaum** [comment]
Side-note: I see the sklearn plot is a horizontal bar plot. Would this be preferable to our vertical one?

**Comment by MarieS-WiMLDS** [comment]
no opinion on the vertical/horizontal choice on my end. We can keep as is.
