### ISSUE TITLE
feat: Enhance skore.cross_validate with cross_validate history

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#563]
### Is your feature request related to a problem? Please describe.

As a data scientist, I don't want my cross_validate plots to be erased on each iteration.   
Sub issue of https://github.com/probabl-ai/skore/issues/544

### Describe the solution you'd like

We want to have a name quite short, but as representative as possible of the execution that took place.  
Do not erase cross_validate on each run, but rather create a new plot with a new name, following this convention: `cv_skore_{estimator}_run_{iter}`.  

### Describe alternatives you've considered, if relevant

`cv_skore_run_{iter}` could be another solution, but the iter number might grow super high very quick. Not what we want.

**Comment by augustebaum** [comment]
What is `estimator` precisely? is it the class name of the estimator?

**Comment by tuscland** [comment]
Giving priority to #504, after completion, this issue might become irrelevant.
