### ISSUE TITLE
feat: Enhance skore.cross_validate with more readable time

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#564]
### Is your feature request related to a problem? Please describe.

As a data scientist, I want the execution time to be displayed in more human readable format.
0.0025 seconds is not readable, nor is 184727647 seconds.

A readable format is:
"10 days, 10 hours, 5 minutes and 12 seconds"

Sub issue of https://github.com/probabl-ai/skore/issues/544  

### Describe the solution you'd like

This might be a solution, but it's only an idea, the tech design is left to the dev reader :)  
```python
import datetime
print(str(datetime.timedelta(seconds=1_000)))
```

**Comment by augustebaum** [comment]
@sylvaincom can you confirm that the new Plotly version of the plot still has this problem? If not, this can be closed

**Comment by sylvaincom** [comment]
IMO it is still a problem, it is display as numeric type and not datetime
