### ISSUE TITLE
Design UI/UX for item historicization

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#568]
Please perform UI/UX research needed for #504 (see epic description).

**Comment by tuscland** [comment]
Initial UI/UX mockups
https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4367-2954&node-type=section

**Comment by rouk1** [comment]
> Initial UI/UX mockups https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4367-2954&node-type=section

If I may this link points to a section named : "Experiment 5 : Digital real estate".
The history experminent section can be found [here](https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4327-8263&t=Ahj0xh4mwqSMHFiW-1).

**Comment by tuscland** [comment]
In order to move forward, we decided to choose the first option:

- display history in the "More/Browse History" menu of an Item.
- when an old item is displayed, a text alerts the user: "⚠ You are viewing an old update (switch to latest)"

**Comment by rouk1** [comment]
Updated version of the screen:

![Experiment selected with feedbacks](https://github.com/user-attachments/assets/599ea5a4-879f-4319-9109-ecb39392e2c9)
