### ISSUE TITLE
UI: automatic refresh screen doesn't work anymore

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#581]
### Describe the bug

We used to have automatic refresh, both on the items values displayed in the view, and in the item menu. It's not the case anymore. I have to refresh the UI by myself and it's frustrating.    

![Capture d’écran du 2024-10-23 11-40-48](https://github.com/user-attachments/assets/a9e4523d-7c1d-4ba0-82cd-962c3ba3d23b)

### Steps/Code to Reproduce

```python
# %% 
from skore import load
project = load("project.skore")
project.put("new", 4)

# %%
# open the skore UI, add new to a view

# %% 
project.put("new", 2)
project.put("new2", 5)
```

### Expected Behavior

I expect to have an automatic update so I don't have to refresh my navigator window.  

### Actual Behavior

It doesn't refresh automatically.  

### Environment

```shell
System:
    python: 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:36:51) [GCC 12.4.0]
executable: /home/marie/anaconda3/envs/skore/bin/python
   machine: Linux-6.8.0-47-generic-x86_64-with-glibc2.35

Python dependencies:
        skore: 0.2.0
          pip: 24.2
   setuptools: 75.1.0
    diskcache: 5.6.3
      fastapi: 0.115.3
 plotly<6,>=5: None
         rich: 13.9.3
        skops: 0.10.0
      uvicorn: 0.32.0
```

**Comment by tuscland** [comment]
I confirm that it is broken.
