### ISSUE TITLE
UI: have a clear way to hide and reopen the left pane

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#583]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when seeing this plus button (on the right) and I don't understand what it does.  

![image](https://github.com/user-attachments/assets/717d0677-7005-4113-84d4-01e2003b5518)

### Describe the solution you'd like

I like the notion solution very much with the two chevrons:  
![image](https://github.com/user-attachments/assets/0b5c9c6a-d331-4cc7-a92d-d2090cbb55ba)

### Describe alternatives you've considered, if relevant

maybe a cross instead of `<<`?  

### Steps

1. [x] draw new design
2. [ ] implement new design

**Comment by anasstarfaoui** [comment]
<img width="760" alt="Capture d’écran 2024-10-23 à 17 31 29" src="https://github.com/user-attachments/assets/3eb612e8-5def-49ac-94fd-cfaa8d6fd095">

Something like this ?

**Comment by MarieS-WiMLDS** [comment]
that's perfect!

**Comment by anasstarfaoui** [comment]
Okay, I update other screens, it will be available on V3 on figma

**Comment by anasstarfaoui** [comment]
Should I close this ticket?

**Comment by MarieS-WiMLDS** [comment]
nope, I'm transferring to ready for dev! (It could have been an epic with two shorter issues, one dedicated to design and the other to dev but... it felt too small to do that)

**Comment by augustebaum** [comment]
Does the chevron need to be moved inside the sidebar? This makes things more complicated; changing an icon is much simpler. What do you think?

**Comment by anasstarfaoui** [comment]
Ideally yes, it would be nice but I'm okay to just swap icons to make it clearer

@MarieS-WiMLDS wdyt?

**Comment by MarieS-WiMLDS** [comment]
I'm ok to swap too!

**Comment by anasstarfaoui** [comment]
Okay then @augustebaum @MarieS-WiMLDS , I'm changing production mockups
