### ISSUE TITLE
Python API to create project

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#716]
The intro example has this:

```py
# create the skore project
subprocess.run(f"python3 -m skore create my_project --working-dir {temp_dir}".split())
```

Which feels odd. We should have proper Python API to create a project. It's totally okay to have a CLI to do that, but our python scripts should be calling Python API w/o the need to do a `subprocess.run` which makes it quite brittle. Doing a proper Python call also makes it very easy to raise the right exceptions when needed.

cc @glemaitre

**Comment by glemaitre** [comment]
I see that right now, there is a `__create` function. Probably, this is fine to expose this function through the Python API and allow the CLI to just call it.

I'm wondering if `click` that is commonly used can make things easy.

**Comment by jerome-probabl** [comment]
Moreover, python3 works primarily on GNU/Linux distributions, and I'm not certain it works on all of them. It does not work on macOS or Windows by default! Finding the correct Python binary can be a nightmare, and we want to avoid this if possible.

**Comment by thomass-dev** [comment]
Actually, we removed the python functions used to create project directly from a script, in favor of a dedicated CLI.
It was a need to force the user to create explicitly the project, to stay in control of the project creation workflow.

But it appears to be inadequate and not user-friendly, so we will re-add a Python API in addition of the CLI.
Thanks!
