### ISSUE TITLE
`put` kwarg API

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#718]
I find it odd that the user has to write

```py
my_project.put("my_gs_cv", gs_cv)
my_project.put("my_df", df)
my_project.put("my_fig", fig)
```

instead of 

```py
my_project.put(my_gs_cv=gs_cv, my_df=df, my_fig=fig)
```

It'd be nicer if we support `**kwargs` here

**Comment by augustebaum** [comment]
Using `**kwargs` for this purpose would feel a little strange to me as I consider the mechanic to be meant for passing options (like in matplotlib).

On the other hand we do support grouped `put` via a dict:
```python
my_project.put(dict(my_gs_cv=gs_cv, my_df=df, my_fig=fig))
```

**Comment by adrinjalali** [comment]
> Using **kwargs for this purpose would feel a little strange to me as I consider the mechanic to be meant for passing options (like in matplotlib).

Doesn't have to be that. From the user's perspective, the code with kwargs looks a lot more natural.

**Comment by thomass-dev** [comment]
I thought that passing key-value pairs as `kwargs` will prevent us to add future optional parameters.
Currently, we can put items one by one, or using a dict of key-value pairs as said by @augustebaum.

We will wait for future user-feedbacks.
