### ISSUE TITLE
Contribution workflow

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#720]
I see it seems most (all) contributions are done via branches in the main repo.

It'd be nice if folks would create PRs from their own forks now that the project is public, and to have only release branches on the main repo. It would also give other contributors the feeling that their contributions are on the same level as "internals"

**Comment by MarieS-WiMLDS** [comment]
hehe, big internal debate, we've been discussing this several times. For now, as we are so few working on it, we kept the easy solution to use only one repo.  
@thomass-dev and @tuscland are the main persons interested in this question.

**Comment by rouk1** [comment]
> Also, if you don't do fork based PRs, your CI is not gonna be PR friendly, which shouldn't be the case, and a contributor like me comes and sees all those odd branches on the main repo, which shouldn't be there.

Hello ! Could you elaborate on this, I do not understand what makes the CI PR unfriendly ?
To me using fork based is cumbersome if you work on a feature as a group as you may have to add your pairs remote to get their work in your clone. SEO wised I'm always puzzled when I stumble a repo fork and looks for the OG one (but that may not be valid).

**Comment by adrinjalali** [comment]
There's a lot of difference in terms of availability of tokens / secrets and env variables between jobs run from forks and jobs run on the main repo.

On GH, all forks are clearly marked as a fork (it's actually quite hard to remove that, you'd need to contact GH customer support), so people see that it's a fork of something else. scikit-learn has over 25k forks, but people are not confused about it.
