### ISSUE TITLE
Using `click` instead of `argparse`

### ISSUE THREAD

**Issue by glemaitre** [probabl-ai/skore#723]
I'm wondering if using `click` would not be better than `argparse`.

IMO, the code is more readable in the `click` "world": cf. https://github.com/glemaitre/skore/blob/click_entry_point/skore/src/skore/cli/cli.py

It comes with nice tool such as the `ClickRunner` to run unit tests.
In the code above, I also configure the color format that would provide something like:

<img width="624" alt="image" src="https://github.com/user-attachments/assets/bead9467-ef1f-4be5-8b72-5ecdd7b73451">

**Comment by augustebaum** [comment]
This was considered; the decision came down to:
- argparse is from the standard library
- there are several 3rd party CLI packages (click, typer, docopt...) which makes it harder to choose

**Comment by adrinjalali** [comment]
Seems like with something like `click`, you can easily have use the python API at the same time as your CLI, which is nice.

**Comment by glemaitre** [comment]
I would really like to revisit this option here. I was looking at how to make the `help` appealing when using the CLI. While this is possible to use a color formater with `argparse`, there is no way to have a system of "grouping" commands.

In our use case here, I can already see that we have several group:

- `create` and `open` (if #917 is addressed): those are related to `skore` and the way to handle `Project`s.
- `launch` that is purely related to skore-UI.

I don't think that some of the CLI commands will be removed in the future and instead I can anticipate that we add more functionality that potentially extend the number of group (things related to skore-hub).

So `argparse` is not enough anymore. To answer the question about why `click` instead of others: I am aware of several packages using it in the scientific ecosystem, some quite recent. Pinging @tuscland since you close this issue.

**Comment by augustebaum** [comment]
Thanks for the extra arguments, this is good to know! When we start adding more commands we can definitely re-weigh the options.

**Comment by glemaitre** [comment]
Another argument is to share options at the global and sub-command level like verbose to allow:

```shell
skore --versbose launch ...
```

and

```shell
skore launch --verbose
```

`click` should nicely support it by allowing boolean operation between the different context. `argparse` does not allow for that as we saw when working on https://github.com/probabl-ai/skore/pull/962#pullrequestreview-2517254865
