### ISSUE TITLE
ci: Add automatically a `needs triage` label to PRs coming from a team outsider

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#728]
We need to highlight PRs coming from a team outsider, to differentiate it from our internal PR.

**Comment by adrinjalali** [comment]
This exactly the kinda thing which is counterproductive to creating a community. There should be no difference between internal and external contributions.

**Comment by tuscland** [comment]
As a company-driven open source project we need ways to support feedbacks, contributions, but also follow a product-oriented workflow.
We will get to a community-driven project when time is ripe.
