### ISSUE TITLE
Move the artifacts from documentation build in a separate branch

### ISSUE THREAD

**Issue by glemaitre** [probabl-ai/skore#733]
In order to not have a bot committing in the `main` branch, it would be a better practice to have the `sphinx` GHA to build the documentation and upload it in a `gh-pages` dedicated branch (only the artifacts).

Such workflow is described here:

https://github.com/sphinx-doc/sphinx/blob/master/doc/tutorial/deploying.rst#github-pages

It is pretty straightforward.

Also, it is handy to have access to the artifacts in the pull-request to get a preview of the build to check if everything went fine with a manual visual inspection. I'm used to do this step in CircleCI with an GHA to redirect to the artifacts but it might be possible to check directly the output if build with GHA (to be investigated).

**Comment by glemaitre** [comment]
Regarding the preview in PR, it seems that pandas already have an actions that can help for that: https://github.com/pandas-dev/github-doc-previewer

**Comment by adrinjalali** [comment]
The docs also create a massive repo as time goes by, and we don't really care about the git history of those files. They really should be in a separate repo.

Locally, a script can create the docs in a folder where one can view them.

**Comment by glemaitre** [comment]
> Locally, a script can create the docs in a folder where one can view them.

You can already do that with `make html`.

> you can build locally the documentation, i'm not a big fan to create a documentation artifact on each PRs.

I disagree here because I found tons of time where this feature was useful for review or even discussion by just going to the PR and redirecting to the rendering without any needs to do anything locally. I'm personally using this workflow in scikit-learn and see other people doing for instance in `skrub` (ping @jeromedockes).

Be aware that the flushing of artifacts is automatically manage by the services so you really have nothing to do.

**Comment by thomass-dev** [comment]
I know, artifacts are by default drop after 90 days. We can even add a github-action to remove artifacts related to PR at closing.

> I disagree here because I found tons of time where this feature was useful for review or even discussion by just going to the PR and redirecting to the rendering without any needs to do anything locally. I'm personally using this workflow in scikit-learn and see other people doing for instance in skrub (ping @jeromedockes).

I reconsider my opinion if people need this feature 😄 .

**Comment by jeromedockes** [comment]
I agree with @glemaitre that it is quite convenient to have circleci build the documentation for a pr's branch and then host it (for some time), because then anyone can look at a rendered example online and give feedback on the api of a new feature without needing to checkout the branch and build the documentation locally
