### ISSUE TITLE
`put_one` vs `put`

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#735]
What's the difference between `put_one` and `put` / `put_item`? The docstring doesn't really say anything.

ref: https://probabl-ai.github.io/skore/latest/generated/skore.Project.html#skore.Project.put_one

**Comment by augustebaum** [comment]
`put_one` isn't really meant to be used, it's more of a convenience method that makes it simpler to write `put`. `put` itself mostly just infers whether the user passed a single key-value pair, or a dict of key-value pairs.

As for `put_item`, the signature shows that the `value` parameter is an `Item`. This is the method that actually persists information. In particular, it's a more direct way to put information where the user can specify its type. See [here](https://probabl-ai.github.io/skore/latest/auto_examples/plot_02_overview_skore_ui.html#storing-strings-and-texts) for an example of using `put_item` to specify that a string is HTML.

`put_one` can be made private I think, and we can document the difference between `put` and `put_item` in more detail.

**Comment by tuscland** [comment]
`put_one` is a non documented API.

**Comment by adrinjalali** [comment]
It's documented: https://probabl-ai.github.io/skore/latest/generated/skore.Project.html#skore.Project.put_one

You might want to make it private then.
