### ISSUE TITLE
UTF-8 Requirement

### ISSUE THREAD

**Issue by adrinjalali** [probabl-ai/skore#737]
https://probabl-ai.github.io/skore/latest/install.html#install mentions the user needs to have their encoding set to UTF-8, but that sounds very odd to me.

First off, people in the far east very often don't have UTF-8, for instance since western oriented developers of UTF didn't realize Chinese and Japanese should NOT be shared in the table. Same thing goes with Arabic and Persian.

So it's quite normal for people to have other encodings in their machine.

I wonder where the requirement comes from, but it certainly isn't a reasonable one.

**Comment by rouk1** [comment]
I think that this warning was added when working on windows support (#475).
Maybe @thomass-dev knows better if this is still relevant.

**Comment by sylvaincom** [comment]
cc @augustebaum

**Comment by thomass-dev** [comment]
I don't remember exactly which one but, some functions (std and third libraries) intends to used implicitly UTF-8 encoding.
It was a shortcut to be Windows compliant. If its blocking, we should deep-dive into the problem.

**Comment by sylvaincom** [comment]
So there is no need to have that warning?

**Comment by rouk1** [comment]
Yes and it has been removed.
