### ISSUE TITLE
refactor: factorize cross-validation logic

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#751]
The code is spread between `items/cross_validation_item.py` and `sklearn/cross_validation.py`.
I find it pretty hard to contribute and to maintain.

I recommend to centralize the logic in a `sklearn/cross_validate/` directory, leaving `items/cross_validation_item.py` just as a class containing data (without business logic).
I recommend to split the code from `sklearn/cross_validation.py` in dedicated files (plot, compute etc.).

In addition, i recommend slightly modifying the code of the `cross_validation` function itself to create item only when necessary. My idea is to create the plot first, show the plot after, and in the late part create the item if necessary.

**Comment by tuscland** [comment]
Also gives us flexibility for future decisions, like monkey-patching sklearn.
