### ISSUE TITLE
Improve documentation cross_validate: be more explicit about what this function provides

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#752]
### Which part of the documentation needs improvement?

The documentation of the function cross_validate.

### Describe the problem found in the documentation

As of now, it doesn't explain what the function provides and does.

### Additional context

improvement suggested by Adrin in https://github.com/probabl-ai/skore/issues/731

**Comment by augustebaum** [comment]
The issue is not very clear ("Suggested improvement" most notably); I linked #763 but it might not be enough.

**Comment by MarieS-WiMLDS** [comment]
Your PR looks sufficient to me :) !
