### ISSUE TITLE
feat: Add polars support

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#758]
### Is your feature request related to a problem? Please describe.

Following https://github.com/probabl-ai/skore/issues/712, we should use polars more than pandas for data frames

### Describe the solution you'd like

The skore project should support Polars dataframes as items

**Comment by augustebaum** [comment]
I've reached a bit of a blocker: polars DataFrames don't have an Index like pandas, so it will display weirdly in the UI. There are different solutions:
- Pretend the first column is an index
- Change the UI so that it doesn't show an empty index column

@sylvaincom do you have an opinion on this?

**Comment by augustebaum** [comment]
Second issue: polars supports storing numpy arrays as values, but then serializing to JSON raises an error:
```
In [12]: polars.DataFrame([{"key": np.array([1, 2])}]).write_json()
---------------------------------------------------------------------------
ComputeError                              Traceback (most recent call last)
<ipython-input-12-f51966bf6b4b> in ?()
----> 1 polars.DataFrame([{"key": np.array([1, 2])}]).write_json()

~/Desktop/skore/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py in ?(self, file)
   2664                 json_bytes = buf.getvalue()
   2665             return json_bytes.decode("utf8")
   2666
   2667         if file is None:
-> 2668             return write_json_to_string()
   2669         elif isinstance(file, StringIO):
   2670             json_str = write_json_to_string()
   2671             file.write(json_str)

~/Desktop/skore/.venv/lib/python3.12/site-packages/polars/dataframe/frame.py in ?()
   2661         def write_json_to_string() -> str:
   2662             with BytesIO() as buf:
-> 2663                 self._df.write_json(buf)
   2664                 json_bytes = buf.getvalue()
   2665             return json_bytes.decode("utf8")

ComputeError: cannot write 'Object' datatype to json
```
unlike pandas which implicitly treats the array as a list.

Should we let the polars exception bubble up (the easiest solution), or wrap the error in our custom exception, or e.g. detect numpy arrays and convert them... what do you think @sylvaincom @thomass-dev?

**Comment by augustebaum** [comment]
> > I've reached a bit of a blocker: polars DataFrames don't have an Index like pandas, so it will display weirdly in the UI. There are different solutions:
> > 
> > * Pretend the first column is an index
> > * Change the UI so that it doesn't show an empty index column
> > 
> > [@sylvaincom](https://github.com/sylvaincom) do you have an opinion on this?
> 
> We could create a fake index for the UI?

Sounds good to me

**Comment by augustebaum** [comment]
Now the only blocking point is https://github.com/probabl-ai/skore/issues/758#issuecomment-2498193897

**Comment by augustebaum** [comment]
After discussion with @thomass-dev, we won't try to emulate Pandas' behaviour: if the polars DataFrame conversion to JSON fails, we'll catch it and wrap in an exception.
