### ISSUE TITLE
fix(docs): Add preview for the examples

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#776]
Currently (once https://github.com/probabl-ai/skore/pull/773 is merged), we have examples without Matplotlib outputs, so there is no preview of example:

<img width="550" alt="Capture d’écran 2024-11-19 à 18 18 34" src="https://github.com/user-attachments/assets/726eff91-38fa-4d13-866e-186d19bdcfad">

The display is not nice, we could do like skrub:

<img width="550" alt="Capture d’écran 2024-11-19 à 18 23 24" src="https://github.com/user-attachments/assets/425de8bf-1b29-4747-8aba-601633468a78">

**Comment by rouk1** [comment]
Skrub use there logo as a default thumbnail. As we do not have a proper logo for now, I'm not really sure that this issue is ready.

**Comment by sylvaincom** [comment]
I mean, we can display whatever to appear more pleasant? Not necessarily a logo but a snapshot of the plotly figures inside the example
