### ISSUE TITLE
feat: Cross-validation reporter with accessors

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#801]
### Is your feature request related to a problem? Please describe.

Current way to access cross_validate is a bit weird for users (skore 0.4.0). It does things on their behalf that they do not really expect (in particular: putting). Also, the value related to this feature exists, but it too scarce to explain a change, and the form of the interaction with the user prevents us from doing more. 

### Describe the solution you'd like

Adding a CrossValidationReporter objects allows to answer the needs and problems listed above, while respecting our needs to keep the change simple for the user.

### Pre-requisites
- Technical specifications
  - [ ] Python: Function signatures and interfaces defined

### Steps

Steps for this epic:
- Adapt Guillaume's PR based on new discussions + test & documentation standards
  - tech: https://github.com/probabl-ai/skore/issues/807
- Enable the import of CrossValidationReporter
  - design: #802 
  - tech: to be created   
- Add back the additional scorings
  - tech: to be created
- Add back the aggregation: 
  - design: https://github.com/probabl-ai/skore/issues/803
  - tech: issue to create once the design issue is ready
- upload the items to activity feed thanks to the attribute `project`, but don't create items without the `put` function
  - no issue yet, waiting for activity feed to be implemented

**Comment by MarieS-WiMLDS** [comment]
## Cleaning necessary  

- remove matplotlib option
- remove former cross_validate function
- other ?

**Comment by augustebaum** [comment]
About the design presented in #802:
- Just to check: the CV results include `fit_time` and `score_time`; should these numbers be shown in the table? Or just the ML-related metrics?
- In the "primary results" we only show the average/best for accuracy and precision even though other metrics have been computed: in reality there would average/best for every metric, right?

**Comment by augustebaum** [comment]
We're currently developing the UI with @rouk1 and this is an example of all the parameters that a RandomForestClassifier has:

![2024-12-09T16_24_56_screenshot](https://github.com/user-attachments/assets/8460dcc0-64c9-4c66-bff1-88b6b9761525)

We'll need a way to show less information here most likely...

**Comment by MarieS-WiMLDS** [comment]
oula, yes indeed! Can we remove all the `None` at least?

**Comment by augustebaum** [comment]
> oula, yes indeed! Can we remove all the `None` at least?

Here is what it looks like:

![2024-12-10T11_41_43_screenshot](https://github.com/user-attachments/assets/9df02144-df02-4892-83a3-c5e913d99b19)

**Comment by anasstarfaoui** [comment]
Let's display maximum 4, and put others inside a tooltip

**Comment by MarieS-WiMLDS** [comment]
We came up with a first solution. I enriched with three new issues: https://github.com/probabl-ai/skore/issues/978, https://github.com/probabl-ai/skore/issues/977 and https://github.com/probabl-ai/skore/issues/976. This epic can be closed.
