### ISSUE TITLE
design(UI/UX): How does the CrossValidationReporter appear in a view?

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#802]
For the MVP, we want to display this: 
- plots:  
   -Compare scores
- primary metrics:
  - mean of the metrics we have by default (it depends on the ML problem, classification or regression)
  - cross validation results (the dict) presented as a dataframe
- storage:
  - model part for now: estimator parameters, cross validation parameters, data split indices

**Comment by anasstarfaoui** [comment]
MVP design: https://www.figma.com/design/Qzjyxv0lPDU2kKtsH9dcp3/Skore---Workstation---High-fidelity-mock-ups---Q3?node-id=4987-450&t=pyz6fCQnQYjfmVcE-4
