### ISSUE TITLE
feat: Cross-validation reporter with accessors (Guillaume's PR improvements)

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#807]
## UX changes

Suggestion to avoid asking the user to do "return_xxx", asking them to give X and y again, and to allow for adding scorings as the current feature does.

With this piece of code, suggested by Guillaume in a discussion this afternoon: 

```python
class CrossValidationReporter:
  def __init__(self, estimator, X, y):
    self.cv_results = sklearn.cross_validation(estimator, X, y)
    self.X = X
    self.y = y
```

We would have this change.   

| before | after |
| --- | --- |
| <pre> from sklearn.model_selection import cross_validate <br> cv_results = cross_validate(classifier, X, y) </pre> | <pre> from skore import CrossValidationReporter <br> reporter = CrossValidationReporter(classifier, X, y) <br> cv_results = reporter.cv_results_ |

And the second option offers all the functions listed in the top comment.

This would answer the need: 
- change quite simple for the user, although not transparent
- possible for them to have exactly the same thing as before

## Suggestion about the "put" and parameter "project".

I'm in favor of having both. Setting `project = project` wouldn't put actually, but it would make it appear in the activity feed. This way, we avoid overloading the items list. So far, our testers are a bit surprised to see something appear in the items sections while they didn't put it, while they just learned that they can make items appear by doing using the put function. 

This will be tacled in next issues.

## Two backends

For now, following a decision taken this morning with the design team (cf this [notion page](https://www.notion.so/probabl/2024-11-22-skore-workshop-with-Ga-l-and-Guillaume-146ef76d36b9808d86cec6da33699d24) for probablers), we will keep only one backend, plotly, to keep it simple and easy to develop.  

## Current features

Some of the current features are not included in this rework and will need to be added back: 
- add scorings (value: avoid having to rerun everything when you notice that you didn't chose correctly the scoring)
- aggregation: I think it cannot be included in the object CrossValidationReporter, it doesn't make sense. I think it would be more something like a new object, CrossValidationComparator.

Enabling to put CrossValidationReporter into an item will be done in a next issue too, once the UI is designed.

This will be done in next issues.

_Originally posted by @MarieS-WiMLDS in https://github.com/probabl-ai/skore/issues/749#issuecomment-2494069151_

### Ready State Checklist

- Specification complete and validated
  - [ ] Full description with validated functional requirements
- Design deliverables
  - [ ] UI/UX mockups #802 
  - [ ] Python: Function signatures and interfaces defined

**Comment by sylvaincom** [comment]
See https://github.com/probabl-ai/skore/pull/749#issuecomment-2498613416

**Comment by tuscland** [comment]
An idea came to mind while reading [this PR code](https://github.com/probabl-ai/skore/pull/847).
It might be interesting to save the arguments provided to the CrossValidationReporter. WDYT?
This would help the user track how the CV operation was originally defined.

**Comment by MarieS-WiMLDS** [comment]
Yes, I agree! All the more that it will be necessary to compute some part of the object that we do not want to compute at first (because too long). I have to list what we want to compute later and then list what is needed.

**Comment by tuscland** [comment]
(It seems related to https://github.com/probabl-ai/skore/issues/557)

**Comment by augustebaum** [comment]
With #847 merged, it might be good to clean this issue/close it and open others for future improvements.

**Comment by MarieS-WiMLDS** [comment]
indeed Auguste! This will close with the integration of the cv item in front.
