### ISSUE TITLE
Activity feed: JSON API

### ISSUE THREAD

**Issue by rouk1** [probabl-ai/skore#814]
# As a frontend developer I want to request the project's activity using an HTTP API.

> Disclaimer: even if this a perfect use case for web sockets, we will stick to a REST endpoint.

## Needs

We need to serialize a list of item version for the frontend to display them from most recent to oldest one.

> [!NOTE]  
> This means that: if a user asks for the last 5 minutes of activity, and one item has changed 2 times during this time frame (same identifier, two different values), they will receive 2 _versions_ of this item.

## Proposed API

`GET` `/api/project/activity?after={creation_datetime}` (fetch the project activity)

##### Parameters

| name    | type     | data type                         | description                                                                |
|---------|----------|-----------------------------------|----------------------------------------------------------------------------|
| `after` | optional | datetime as UTC string (iso 8601) | A search filter (every item that have been added after the given datetime). Adding this parameter will allow frontend to only request new data after the initial call. |

##### Response

| http code | content-type                     | response              | description                                    |
|-----------|----------------------------------|-----------------------|------------------------------------------------|
| `200`     | `application/json;charset=UTF-8` | `[{...}, {...}, ...]` | A list of item ordered by descending `create_at` datetime. |

###### Data layout

```json
[
  {
    "name": "md_item",
    "media_type": "text/markdown",
    "value": "# hello",
    "created_at": "2020-07-10 15:00:00.000"
  },
  {
    "name": "df_item",
    "media_type": "application/vnd.dataframe+json",
    "value": {},
    "created_at": "2020-07-10 14:00:00.000"
  },
  //...
]
```

**Comment by rouk1** [comment]
@augustebaum & @thomass-dev may I have your review on this ?

**Comment by tuscland** [comment]
Note: warnings are removed from this first iteration.

**Comment by rouk1** [comment]
> * Can we still leave without identifiers for items or anything that is stored? It feels like we are pushing the model to its limits for nothing.

Hmmm your right I forgot that. Editing...

**Comment by rouk1** [comment]
> Note: warnings are removed from this first iteration.

It could be quite easy to add warnings.
A warning could have a media_type and be persisted in a dedicated repository (like we did for views).

```json
[
  {
    "name": "High class imbalance",
    "media_type": "application/vnd.warning+text",
    "value": "It seems that you have a classification problem with at least one class with...",
    "updated_at": "2020-07-10 15:00:00.000",
    "created_at": "2020-07-10 15:00:00.000"
  }
  //...
]
```

```

**Comment by augustebaum** [comment]
Does `after` refer to `created_at` or `updated_at`? Should there be `created_after` and `updated_after` parameters instead?

**Comment by augustebaum** [comment]
> Disclaimer: even if this a perfect use case for web sockets, we will stick to a REST endpoint.

Can you give more details? Why is it a perfect use-case, and if so, why would we not do that?

**Comment by rouk1** [comment]
> Does `after` refer to `created_at` or `updated_at`? Should there be `created_after` and `updated_after` parameters instead?

Those naming comes directly from what we have in the project API. I prefer to have consistent naming for the same thing. 

> > Disclaimer: even if this a perfect use case for web sockets, we will stick to a REST endpoint.
> 
> Can you give more details? Why is it a perfect use-case, and if so, why would we not do that?

It's an activity feed. The term _feed_ could let you think that it's real time. Hence a real time communication protocol sound s appropriate. But to implement this without some message broker we would need to **watch** the db changes. As far as I know, because we use diskcache, we cant have easily access to the sqlite driver to register some [hooks](https://www.sqlite.org/c3ref/update_hook.html). As a first approach polling with incremental search will have good performances and abstracts us from complex communication between process.

**Comment by augustebaum** [comment]
> each item will have only [a] creation_date [not a update_date]

Works for me

**Comment by rouk1** [comment]
edit: added @augustebaum feedbacks

**Comment by thomass-dev** [comment]
Perfect proposition, all good for me, thanks @rouk1 .

**Comment by thomass-dev** [comment]
Just a naive question: what about mixing history and activity?

If you ask for the last 5 minutes activity, and one item has changed 2 times during this period.
Would you received the two versions of the items? Or the latest one?

**Comment by rouk1** [comment]
> Just a naive question: what about mixing history and activity?
> 
> If you ask for the last 5 minutes activity, and one item has changed 2 times during this period (same identifier, two different values). Would you receive the two versions of the items? Or the latest one?

You should receive all events that happens during that time frame. Hence 2 versions of your item.

**Comment by thomass-dev** [comment]
Can you update your description that way?

**Comment by rouk1** [comment]
> Can you update your description that way and make a quick reference?

Done, is it ok for you ?

**Comment by rouk1** [comment]
Moving this to the related epic.
