### ISSUE TITLE
refactor(cross-validation): Decouple computation from storage in Project

### ISSUE THREAD

**Issue by augustebaum** [probabl-ai/skore#827]
sub-issue-of: #807 

Currently the cross-validation feature is used via the `skore.cross_validate` function:

```python
# Computes CV information AND saves information in the project
cv_results = skore.cross_validate(clf, X, y, cv=5, project=project)
```

The cross-validation computation should be decoupled from the storage process, which can be done by introducing an intermediary class:
```python
# Saves information in the project
reporter = skore.CrossValidationReporter(clf, X, y, cv=5)
cv_results = reporter.cv_results
project.put("cv", reporter)
```

This might be done by re-purposing `skore.item.CrossValidationItem`, and making `put` aware of how to deal with such an object.
This issue is not concerned with adding any functionality to `CrossValidationReporter` (such as accessors and other methods), only with refactoring existing behaviour.

### Additional context

See also #751 #749

**Comment by augustebaum** [comment]
@MarieS-WiMLDS I'm under the impression that `skore.cross_validate` should be completely removed in favor of CrossValidationReporter. Can you confirm?

**Comment by MarieS-WiMLDS** [comment]
yes, I confirm!

**Comment by augustebaum** [comment]
I've reached somewhat of a roadblock.

Currently, to get the cross-validation plot from skore, you have to go through the item:
```python
cv_results = skore.cross_validate(...)
cv_item = project.get_item("cross_validation")
cv_item.plot
```

Since I'm moving all the logic from `CrossValidationItem` to `CrossValidationReporter`, it makes sense to also give `CrossValidationReporter` control of the plot:
```python
reporter = skore.CrossValidationReporter(...)
reporter.plot

# You can still get the item:
cv_item = project.get_item("cross_validation")
# But it doesn't have the plot itself anymore
cv_item.plot_bytes
# b"..."
```

But now, what if a user has a `CrossValidationItem` (e.g. that they saved long ago) and wants to see the plot, like we've been doing in the docs?

### Option 1: `Project.get` returns a `CrossValidationReporter`

As a user, I would first try to `get` the item:
```python
reporter = skore.CrossValidationReporter(...)
project.put("cross_validation", reporter)

stored_reporter: CrossValidationReporter = project.get("cross_validation")
stored_reporter.plot
```

However, currently `.get` gives you the cross-validation results dict, not a full `CrossValidationReporter`.

Unfortunately, converting a `CrossValidationItem` back to a `CrossValidationReporter` is hard and might be out-of-scope for skore: for example, currently `CrossValidationItem` does not store the estimator (but just some information like the class name).

### Option 2: Leave `.plot` in `CrossValidationItem`

That is, what we have already:
```python
cv_item = project.get_item("cross_validation")
cv_item.plot
```

This is easy, but it means that users will keep having to interact with `CrossValidationItem`, and it keeps some logic in `CrossValidationItem` which this issue aimed to eliminate in the first place.

Still, if we consider that getting the plot from a previously-saved cross-validation run is an expert-only/rare use-case, then we might be able to live with the weirdness.

### Option 3: Expose `plot_cv_results`

The plot is computed from a cross-validation dict by a private function, `plot_cv_results`; we might simply make it public, so that a user can re-compute the plot from a cross-validation dict. It feels a little off, but it's easy and does the job.

**Comment by augustebaum** [comment]
For now I will most likely go with option 2 because it's the easiest (requires the least changes)

**Comment by thomass-dev** [comment]
> But now, what if a user has a CrossValidationItem (e.g. that they saved long ago) and wants to see the plot, like we've been doing in the docs?

It's perfect time for breaking-changes, as long as we don't have users. Don't worry about retro-compatibility.

**Comment by augustebaum** [comment]
This is adapted from a live discussion with @thomas.

Sorry about the wording; my comment is not about breaking changes/backwards compatibility. The user story is simply: the user `put` a `CrossValidationReporter`, and later they want to get the plot from Python again. Right now their only way to do this is with something like
```python
cv_item = project.get_item("cross_validation")
plotly.io.from_json(cv_item.plot_bytes.decode("utf-8"))
```
which is not great.

> If you `put` a `CrossValidationReporter`, I expect you to `get` a `CrossValidationReporter`. And to be able to see the plot back.

This is also the expectation of @rouk1, and I generally agree with it. However, this is hard, because we don't have control over what the user gives us.

- One compromise is that we could reserve the right to refuse the `put` if what the user gave us is too exotic
	- But the user might reasonably ask: "You let me compute the plot and everything, why can't I `put` now?"
	- Also, `CrossValidationReporter` is a complex object with several attributes: it would suffice for just one of them to be too exotic for us to refuse `put`ting
- Another compromise might be to say: we won't save the hard stuff anyway, e.g. just the plot
	- But then the user might feel tricked because they got a `CrossValidationReporter`, so they should have access to everything they had before they `put`, not just the plot

To conclude we decided that we can live with the above-mentioned solution for now, until this problem is further elucidated.
