### ISSUE TITLE
feat: Question mark pointer is kind of weird

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#837]
### Is your feature request related to a problem? Please describe.

An item is added to a view. I place my mouse cursor over an item key in the left explorer pane. The cursor turns into a question mark.

### Describe the solution you'd like

The cursor turns into a finger pointer.

The reason is that clicking the item key will scroll the view to the item's position, so that means the user expects a action. The question mark does not convey this meaning.

### Describe alternatives you've considered, if relevant

Bare pointer cursor.

**Comment by augustebaum** [comment]
I was also wondering about this

**Comment by rouk1** [comment]
The idea was to let users know that clicking on this may help them find the relevant item in the left pane. Sounds that it did not work ^^ It has been changed #851.
