### ISSUE TITLE
fix(docs): The cross-validation plotly figure does not appear in the doc

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#845]
In the examples gallery of the documentation, we must display the following code for the plotly figure to automatically appear in the notebook:
:
```python
from skore import cross_validate

cv_results = cross_validate(Ridge(), X, y, cv=5, project=my_project)

fig_plotly = my_project.get_item("cross_validation").plot
fig_plotly
```
But when a user copy-pastes this code snippet in his notebook, the plotly figure appears twice.

How could we make the plotly figure appear automatically in the documentation with just:
```python
from skore import cross_validate

cv_results = cross_validate(Ridge(), X, y, cv=5, project=my_project)
```

Maybe @augustebaum? 🙏

**Comment by augustebaum** [comment]
Hopefully this will be closed by #847 because we won't automatically show the plot anymore

**Comment by MarieS-WiMLDS** [comment]
closing it because as Auguste says, it will not be relevant with next version.

**Comment by sylvaincom** [comment]
But we still want the plot to appear in the doc?
