### ISSUE TITLE
fix(docs): Update the GIF link in the README

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#873]
Following https://github.com/probabl-ai/skore/pull/870, the GIF will be stored in our own repo. For the README not to break, on PyPi as well, how can we update the GIF link in the REAMDE? cc @thomass-dev

**Comment by thomass-dev** [comment]
Good point, i will do some tests on `TestPyPI` and update the link in the README.

**Comment by thomass-dev** [comment]
We just have to change the url, and its works. All media stored via Git-LFS are also available.
Check https://media.githubusercontent.com/media/probabl-ai/skore/git-lfs/sphinx/_static/images/2024_10_30_skore_demo.gif 😄 .

**Comment by sylvaincom** [comment]
Thanks!
