### ISSUE TITLE
Skore UI doesn't show the database content

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#887]
### Describe the bug

Skore UI doesn't show the database content

### Steps/Code to Reproduce

[Capture vidéo du 09-12-2024 15:52:00.webm](https://github.com/user-attachments/assets/2a1436a4-6ce5-41ce-9eba-328560c632b5)

Steps:
- create a project
- launch
- create & put items
- during launch, overwrite
- see that old items still exist (despite Fn + F5)
- launch again
- see that old items don't exist anymore

### Expected Behavior

I expect the UI to reflect exactly the database.

### Actual Behavior

I checked that:
- I was on the correct folder
- I was using the correct virtual env
- I forced a new install with a new make install and make build-ui. 

### Environment

```shell
git checkout 69fa3c8 (= version 0.4.1) & cherry-pick bcb8bf6d2f8ed1d589c00dd382bd2857965321af (but I think it's still the case at the current level, as of Dec 9th)
```

**Comment by thomass-dev** [comment]
Please can you test on latest commit instead?

**Comment by rouk1** [comment]
> I think we have a quick and dirty solution. What do you think @rouk1 @augustebaum : instead of instantiating diskcache once, we can instantiate it at each call? We lose performance, but gain robustness...
> 
> -> #892

Let's go ! It is painful to shutdown the server when overwriting a project.
