### ISSUE TITLE
There is a difference between the score and r2 in a regression task

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#906]
### Describe the bug

There is a difference between the score and r2 in a regression task, while it shouldn't because by default, scikit learn uses r2 as a scoring.

### Steps/Code to Reproduce

to come. 

### Expected Behavior

r2 and default score by scikit-learn should be iso in a regression task. 

### Actual Behavior

![image](https://github.com/user-attachments/assets/655f6664-cb4e-42d8-9aaa-a226acd55818)

### Environment

```shell
skore version 0.4.1
```

**Comment by augustebaum** [comment]
Attempt to reproduce using Lasso:

```python
def prepare_cv():
    from sklearn import datasets, linear_model
    diabetes = datasets.load_diabetes()
    X = diabetes.data[:150]
    y = diabetes.target[:150]
    lasso = linear_model.Lasso()
    return lasso, X, y

lasso, X, y = prepare_cv()

from skore import CrossValidationReporter

reporter = CrossValidationReporter(lasso, X, y, cv=3)

reporter._cv_results
# {
#     'test_r2': array([0.3315057 , 0.08022103, 0.03531816]),
#     'test_score': array([0.3315057 , 0.08022103, 0.03531816]),
#     'fit_time': array([...]),
#     'score_time': array([...]),
#     'estimator': [Lasso(), Lasso(), Lasso()],
#     'indices': {...},
#     'test_neg_root_mean_squared_error': array([...]),
#     'fit_time_per_data_point': [...],
#     'score_time_per_data_point': [...]
# }
```

**Comment by MarieS-WiMLDS** [comment]
yes, this issue is still in triage because I can't reproduce the error, and obviously I took a screen capture of the bug, but not of the code leading to the bug... :(

**Comment by augustebaum** [comment]
Feel free to re-open when you can reproduce
