### ISSUE TITLE
fix(docs): Improve installation guide

### ISSUE THREAD

**Issue by sylvaincom** [probabl-ai/skore#928]
Follow-up on https://github.com/probabl-ai/skore/pull/927

Inspiration from skrub: https://skrub-data.org/stable/install.html

Add tabs:

https://github.com/user-attachments/assets/c665d355-ba02-462f-8da0-ee4ebcebca0d

**Comment by MarieS-WiMLDS** [comment]
I don't see anything in the PR linked which indicates the improvements required ; should I wait for this issue for the release as it's P0?

**Comment by sylvaincom** [comment]
Should be good now
