### ISSUE TITLE
why is the last version not labelled as the stable version in the docs?

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#943]
### Describe the bug

![Capture d’écran du 2024-12-13 08-54-08](https://github.com/user-attachments/assets/fda2d003-b484-4567-9ab0-5de52ab2236a)

### Steps/Code to Reproduce

https://skore.probabl.ai/0.5/

### Expected Behavior

no red "bandeau" at the top

### Actual Behavior

there is a red "bandeau"

### Environment

```shell
website
```

**Comment by thomass-dev** [comment]
I think it's only a browser cache problem. 

![image](https://github.com/user-attachments/assets/63eaabe6-a17d-4d3e-a512-21c60836840b)
![image](https://github.com/user-attachments/assets/7dc6b890-00a1-4721-ad66-0fdf31ca7257)

**Comment by MarieS-WiMLDS** [comment]
cache issue, thanks Thomas for the fix & help!
