### ISSUE TITLE
Avoid promoting Probabl when not necessary

### ISSUE THREAD

**Issue by glemaitre** [probabl-ai/skore#957]
In one of the example, I can spot the following quote:

<img width="746" alt="image" src="https://github.com/user-attachments/assets/535cd2db-47aa-4d0a-b0d8-a371be52b670" />

I don't think that we should mention Probabl and refer to the website. I think it is completely fine to start supporting a library and it will be irrespective from being develop by Probabl.

**Comment by tuscland** [comment]
Hello Guillaume,

Skore is a company-led initiative developed by the Product team at Probabl.
It is therefore promoted as such.

**Comment by tuscland** [comment]
Reconsidering this issue, because I read too fast and missed the proper context.

You are right @glemaitre there is no need to mention Probabl, or link to its website.

We just need to keep everything that's after the last comma.
@sylvaincom could you please adjust?
