### ISSUE TITLE
[contribution] make test

### ISSUE THREAD

**Issue by MarieS-WiMLDS** [probabl-ai/skore#991]
### Is your feature request related to a problem? Please describe.

I'd like to be able to run the tests very easily and quickly, without knowing what's behind, pytest or anything else.

### Describe the solution you'd like

make test

**Comment by thomass-dev** [comment]
@augustebaum i remember you had a target in your local Makefile to do so?

**Comment by MarieS-WiMLDS** [comment]
yes, I meant quickly accessible.

**Comment by glemaitre** [comment]
Just a thought regarding `Makefile`: it does not work on Windows.

Some alternatives to know about:

- `spin`: https://github.com/scientific-python/spin. The idea is to provide consistent developer commands across the scientific ecosystem that works and all platforms. It is used in NumPy, SciPy, scikit-learn as examples
- `pixi`: https://pixi.sh/latest/. This is more generic tools. In addition to manage environment for instance for the CI, it provides a way to define `tasks` that is exactly what you need here. We give it a "spin" in skrub.

#### Usage as a user

```shell
spin tests
```

```shell
pixi run tests
```

I don't think it is a priority right now but it could be great to evaluate those solutions. Feel free to open a specific issues particularly for this feature.

**Comment by glemaitre** [comment]
> The makefile is only for contributors use.

Contributors can still have Windows :). The tools mentioned are really crafted for contributors/developers tool not end-user.

**Comment by augustebaum** [comment]
That's an issue for sphinx as well, since we build it with `make html`. Maybe we could just use `sphinx-build` directly, like they explain in the [docs](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build)

**Comment by thomass-dev** [comment]
For now, we all use unix-like OS compatible with Makefile. IMO, keep moving, and come back to your suggestion when we have to.
